---
title: "Software Engineering I"
verify: none # no executable cells
---

## Intro lecture

All the course material (including these notebooks) can be found at https://github.com/smagurauskas/software-engineering.

Lectures will be held in English.

## What is Software Engineering?

Software engineering can be described *programming over time*.

Software engineering deals with such topics as:
- How to scale development efforts
- How to ensure that the project is maintainable for as long as it is needed
- Making trade-offs in the system design
- How to ensure the quality of software being built
- And many more...

***

IEEE defines software engineering as:

> the application of a systematic, disciplined, quantifiable approach to the development, operation, and maintenance of software; that is, the application of engineering to software

***

Older definitions were:

> the practical application of scientific knowledge to the design and construction of computer programs and the associated documentation required to develop, operate, and maintain them

and

> the technological and managerial discipline concerned with systematic production and maintenance of software products that are developed and modified on time and within cost estimates

***

The word "*engineering*" itself is defined as:

> engineering is about applying that knowledge to solve real-world problems with limited resources cost-effectively

and

> In engineering, science and practice are applied to generate potential solutions to the real-world problem, and engineering economics is used to identify the most cost-effective one

## Today's lecture agenda

1. Information about the course and lectures
2. What the lab classes will look like
3. Quick intro into Pull Requests
4. Quick intro into .NET and C#

## Course material

All these notebooks are versioned and placed here https://github.com/smagurauskas/software-engineering.

Pull requests for changes are welcome!

Additional lecture material *might* be placed at [https://emokymai.vu.lt](https://emokymai.vu.lt). Will let you know during the lecture if there are any updates there.

*If you were not added as a member of the course in emokymai/VMA/moodle - write me an email and I will add you.*

## Lecture format

- Lectures are 3 *academic* hours long.
- That means ~2 hour long lectures.
- Will try to have a 50 minute lecture, 20 minute break, and then another 50 minute lecture.

The course is worth 10 ECTS credits. Most of it comes from individual work.

## Purpose of the course unit

The purpose of this course unit is to provide overview and hands-on experience in modern software engineering practices, putting emphasis on web-based application development and C#.

### Learning outcomes of the course unit

- Design, implement and develop applied programs, apply code reviews;
- Apply knowledge of software systems engineering, make qualified design and architectural decisions while expanding the functionality of the developed system;
- Combine theory and practice using .NET framework technologies and developing OO application systems;
- Develop the knowledge about data types, named and optional arguments as well as other new features of C# programming language;
- Understand common automated software testing practices and can apply them using the C# and .NET framework;
- Develop the knowledge about the software development life cycle, understand how the web applications are deployed and monitored;
- Program in C# independently and in a team, applying basic OO design templates using C# programming environment;
- Recognize the need for continuous learning and will have the initial skills;
- Work in the team - on site and remotely.

#### The true goal

Yes:
- Learn the principles
- Learn to reason about software engineering problems
- Learn to apply the principles in practical scenarios

Not:
- Become an expert in specific technologies

::: {.fragment}
This doesn't mean that that it is ok be ignorant of the technology you are using.
:::

## Philosophy behind the course

- Code is a liability
- Writing code is not the end of it
- Initial development effort is only the most obviously visible part of the cost
- Code is read more often than it is written
- *Learning to learn* a technology is more important than *learning a technology*

## Lab classes

Students form teams of ~4 students and develop a product together during the semester. Teams work in mini 1 week sprints and present the progress during the lab class each week.

Students evaluate themselves and their team members each week according to the individual contributions that week. Final lab assignment grades depend on these self evaluations.

### Self evaluation example

Each week, each student gets some fixed amount of points that can be distributed among their team members based on based on justification provided.

Consider an example below where each student has 10 points to distribute among their team members each week:

| Week   | Student A | Student B | Student C | Student D |
|--------|-----------|-----------|-----------|-----------|
| 1      | 10        | 10        | 5         | 15        |
| 2      | 11        | 9         | 15        | 5         |
| 3      | 20        | 0         | 5         | 15        |
| 4      | 10        | 10        | 10        | 10        |
| Total  | 51        | 29        | 45        | 45        |
| Dist.  | 100%      | 57%       | 88%       | 88%       |

Lab professor awarded group 1.2 points for settled lab assignment.

Students individually receive:

| Student   | Individual grade     |
|-----------|----------------------|
| Student A | 1.2 (100% of 1.2)    |
| Student B | 0.7 (~57% of 1.2)    |
| Student C | 1.1 (~88% of 1.2)    |
| Student D | 1.1 (~88% of 1.2)    |

### General requirements for lab assignments

General requirements:
- **Projects should be backend dominant**.
- **All commits must be reviewed via pull requests**. 
- Project must be versioned in GitHub.
- Project must be a web application based on ASP.NET. UI layer framework/technology can be selected freely.
- Goal is to have at least 1 real user at the end of the semester.

## Evaluation

- Exam in written form (max 5.0):
    - Exam can be taken only if all 3 of the Lab assignments are settled
    - Exam can be taken only when total amount of points collected during the semester is 3.0 or more
    - Exam is considered to be passed if at least 1.5 out of 5 points are collected

::: {.fragment}
- Laboratory assignments (max 5.0)
    - Three assignments (1.5 + 1.5 + 2.0)
:::

::: {.fragment}
- Additional points (max 1.0):
    - Outstanding performance, demonstrated during the course
    - Contributing to these course notebooks
:::

::: {.fragment}
Maximum available score from Laboratory assignments + Additional points is **5.5**.
:::

## Lab assignment #1

Deadline: week 7.

Official goal: to develop an web application using the material covered in 1-6 lectures.

Unofficial goal: to develop an app in ASP.NET that has basic functionality of assigned APP. Understand the usage of GitHub, coding in team principles. Prepare foundation for future work. Learn to code review yourself and take the feedback when getting one.

Points: 1.5

1. Application can be interacted with using *some* sort of interface. There exists at least one user scenario, which can be demonstrated end to end.
2. Creating and using your own `class`, `struct`, `record` and `enum`. 1 type must be immutable.
3. Property usage in `struct` and `class`.
4. Named and optional argument usage.
5. Extension method usage.
6. Iterating through collections the right way.
7. Using a stream to load data (can be from file, web service, socket etc.).
8. LINQ to Objects used where appropriate (methods or queries). If LINQ is not used in a particular scenario, provide a justification.
9. Implement at least one of the standard .NET interfaces (`IEnumerable`, `IComparable`, `IComparer`, `IEquatable`, `IEnumerator`, etc.)
10. All changes reviewed via pull requests; each PR must have description explaining what was done and why. Each team member must have authored at least 3 merged PRs and reviewed at least 3 PRs from teammates. PR is counted as reviewed only if there are any meaningful comments and discussions.
11. Uniform coding style is used throughout the project.

## Lab assignment #2

Deadline: week 11.

Official goal: continue developing an app while working in groups while using material covered in 7-10 lectures.

Unofficial goal: start using database and testing the project. Deepen the functionality of application while being creative.

Points: 1.5

1. Relational database and Entity Framework is used for storing all the data.
2. Create a generic type with generic method. Demonstrate how generics removed duplication.
3. Create at least 1 exception type and throw it; meaningfully deal with it, by attaching custom handling logic.
4. Usage of `async`/`await`, no IO is performed synchronously.
5. Identify shared memory scenario and deal with it using concurrent collections or appropriate synchronization mechanisms.
6. Dependency Injection is used everywhere where reasonable, no **dependencies** are created manually with `new`.
7. Unit and integration tests coverage at least 50%.
8. All changes reviewed via pull requests; each PR must have description explaining what was done and why. Each team member must have authored at least 3 merged PRs and reviewed at least 3 PRs from teammates. PR is counted as reviewed only if there are any meaningful comments and discussions.
9. Uniform coding style is used throughout the project.


## Lab assignment #3

Deadline: week 15.

Official goal: continue developing an app while working in groups while using material covered in 11-14 lectures.

Unofficial goal: think about the end-user experience, deepen the functionality of application while being creative. Finish up an MVP version of your application.

Points: 2.0

1. Short video (4 to 6 minutes) is prepared, which showcases how the application works and it's features. Key architectural and code design decisions can also be shown. Must be uploaded to some public video hosting service (i.e. YouTube) or provided as a file. 
2. Application is in a stable state. Additional user flows could be asked to be shown during the presentation.
3. Value proposition of the application can be clearly articulated.
4. Application is shown to solve the problem the students have defined.
5. Unit and integration test coverage is at least 80%.
6. Entity Framework migrations are used and run automatically.
7. CI pipeline is set up which gates each pull request, it must have automated tests check + at least 1 extra gate apart from tests.
8. Application provides live metrics or monitoring for its health and performance (OpenTelemetry or similar).
9. All changes reviewed via pull requests; each PR must have description explaining what was done and why. Each team member must have authored at least 3 merged PRs and reviewed at least 3 PRs from teammates.
10. Uniform coding style is used throughout the project.

Bonus points (max 0.5):
1. Application is hosted in some environment and is accessible through a public domain name. All students in the group must be able to explain how to the deployment setup works.
2. Metrics observability tool (e.g., Prometheus, Grafana, OpenTelemetry) is integrated and has meaningful dashboards and alerts set up.

## Planned lecture topics

These are general guidelines on what the lecture are going to be about. It is possible that if the topics might shift a bit during the semester.

### Ideal scenario

- You try something yourself
- Then you listen to the lecture about what you just tried
- You try again with the new knowledge

### Lecture 2

- Web services: 
    - What are the web services?
    - What is HTTP(S)?
    - What are REST, GraphQL, SOAP and gRPC?
- Developing web services using ASP.NET

### Lecture 3

- Building graphical web UIs with ASP.NET
- Intro into Agile software development

### Lecture 4

- .NET data types
- Classes and structs in C#
- Generic types and methods
- Type conversions
- Standard .NET interfaces
- Creation of objects and object lifecycle
- SOLID

### Lecture 5

- Working with persistent data
- Reading and write the data
- Collections
- Delegates, anonymous methods and lambda expressions

### Lecture 6

- Introduction to LINQ
- Working with data
- Extension methods
- Dependency injection

### Lecture 7

- Unit and integration testing
- Writing tests in .NET

### Lecture 8

- Working with databases
- Introduction to ORMs and Entity Framework
- Using LINQ when working with ORM

### Lecture 9

- Software system construction (SWEBOK)
- Business needs analysis (BABOK)
- Software modification and maintenance
- More on generic types in C#

### Lecture 10

- Multi-threading in C#
- `async` and `await` keywords and their usage
- Concurrent collections

### Lecture 11

- User interfaces and user experience

### Lecture 12

- Improving the software development process
- Automated tools for code quality assurance (static analysis)
- Software deployment
- Continuous integration and deployment

### Lecture 13

- Monitoring and observability

### Lecture 14

- Design patterns
- Modern OO architectures overview

### Lecture 15

- Thinking about the performance in C#
- Preparation for exam

## Exam

Exam will be some combination of this:
- Open ended questions on general software engineering principles, i.e. code reviews, unit and integration testing, design patterns etc.
- Circle the correct answer(s) questions - snippet of C# code, what will be it's output?
- Type in the answer - what will the code print out?
- Complete the code - part of the C# code is missing, complete the code to get the desired result.
- Pull request review - review the pull requests and provide the comments.

## Literature

### Official literature
1. Software Engineering at Google: Lessons Learned from Programming Over Time.
2. C# in Depth - Jon Skeet.
3. The Pragmatic Programmer: your journey to mastery - Andy Hunt.
4. The Art of Unit Testing: with examples in C# - Roy Osherove.

and more... check the course description for the full info.

#### Other highly recommended literature
1. Accelerate: The Science of Lean Software and DevOps: Building and Scaling High Performing Technology Organizations. 
