---
title: "Web frontends"
verify: none # no executable cells
---

Web frontends (*webpages* or *websites* or *web app*) developments allows to deliver programs with rich user interaces served by web browsers and are delivered via HTTP(S) protocol.

***


Web predominantly uses `HTML`, `CSS` and `JavaScript` languages:

::: {.fragment}
- `HTML` allows to set the structure of elements rendered on web page.
:::
::: {.fragment}
- `CSS` allows to change the styles of these rendered elements.
:::
::: {.fragment}
- `JavaScript` allows to add dynamic interactions to the web page.
:::

***

Server returns an `html` file to the browser, and then browser figures out how to display that to the user (aka renders it).

```html
<h1>Hello class!</h1>
```

***

```{=html}
<html>
  <body>
    <h1>Hello class!</h1>
  </body>
</html>
```

::: {.content-visible unless-format="revealjs"}
Websites can be served to users as simple static `HTML` files. But static websites have limited capabilities - they cannot dynamically update their content with new data. In order for website to dynamically adapt to new data it cannot be static, but it needs to be rendered dynamically instead. Rendering in this case means assembling `HTML` document, that can be taken by browser to display the website to user.
:::

### HTML

`HTML` stands for Hypertext Markup Language.

`HTML` is a markup language meaning that it does not have capabilities of traditional programming languages to sciprt algorithms, but it is instead used to define structure of the document.

```html
<html>
    <head>
        <title>Title for this document</title>
    </head>
    <body>
        This is a very simple HTML document
    </body>
</html>
```

***

Although `html` looks very similar to `xml`, it is incorrect to state that any `html` document is also an `xml` document.

Instead they both share common parent language - [SGML](https://en.wikipedia.org/wiki/Standard_Generalized_Markup_Language).

```{mermaid}
graph TD
    SGML --> HTML
    SGML --> XML
```

***
#### Elements and tags

`HTML` markup consists of elements. Elements consists of opening and closing tags.

Start tag is written by specifying element name between `<` and `>`, i.e. `<div>`.

End tag is written by specifying element name between `</` and `>`, i.e. `</div>`. The only difference between opening and closing tags are the `/` symbol following `<`.

::: {.content-visible unless-format="revealjs"}
Every[^1] opening tag must have a corresponding closing tag.

Element can be opened and closed in same tag, by prepending `/` before the closing symbol `>`, i.e. `<div />`. This is used in cases where element does not have any inner content and is primarily used for some rendering purposes.

[^1] - in most of cases. This would be true in `XML`, but since `HTML` is not `XML`, there are some cases, where it is a legit `HTML` syntax for opening tag not to have a closing tag.
:::

***
#### HTML syntax quirks

There are some syntax quirks that are valid for `html` documents, but would be invalid `xml` documents, i.e. in the example below, omitting the `<body>` opening tag [would technically be valid](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission):

```html
<html>
text text text
</body>
</html>
```

***
#### Attributes

`HTML` elements can also have attributes, just like `XML` elements have.

Attributes are specified in start tag between element name and closing `>`.

`<a href="#">hello</a>` element has an attribute `href` with the value of `#`.

Elements can have more than one attribute.

***
#### Comments

Comments in `HTML` documents are specified between `<!--` and `-->` tags.

An example comment in `HTML` looks like this: `<!-- this is a comment -->`.

Comments are ignored when browser renders the document.

***
#### HTML document structure

`HTML` are always wrapped in `<html>` element. Every document must have this element as the root element.

Immediately inside `<html>` element there can be `<head>` element. `<head>` element is not rendered by the browser directly, but rather it can contain various references and other metadata for the page. Examples of such references are inlined or imported `js` scripts, references to `css` files or other metadata elements such as `<title>` which specifies the title of the page to be displayed by the browser.

The `<body>` element comes next. `<body>` element contains other children elements that will be rendered by the browser into an UI.

::: {.content-visible unless-format="revealjs"}
`HTML` has a large selection of elements for rendering the UI, which can be found [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element). There are elements for different purposes: from `<div>` which is used for very generic wrapping purposes, to `<table>` which is used to conveniently display rendered tables.

Check [this reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) to learn more about the available elements and how to use each of these elements.
:::

***

```html
<!-- very simplistic example of an html document with no style or interactivity -->
<div>text wrapped in container</div>
<b>text but bold</b>
<button>pushable button</button>
```

***
```{=html}
<html>
    <head>
        <title>simple document</title>
    </head>
    <body>
        <div>text wrapped in container</div>
        <b>text but bold</b>
        <button>pushable button</button>
    </body>
</html>
```
::: {.notes}
Static `HTML` documents can be tested by simply saving them as `.html` files and the opening them with the internet browser application.
:::

### CSS

`CSS` stands for Cascading Style Sheets. `CSS` is a language for specifying the styling for the `HTML` documents.

`CSS` styling includes such use cases as `width` or `height` of the elements, `colors` of these elements, font sizes and families, how and when should be elements be wrapped into new lines and more.

::: {.content-visible unless-format="revealjs"}
`html` element references usually will also contain information about the available style options for these elements.
:::

***

Sample `css` file:

```css
.blue-box
{
    background-color: #0000FF;
    width: 100px;
    height: 100px;
}
```

This `css` would be applied to an `html` element which has a `class` attribute with `.blue-box` name.

***

`css` can be applied to `html` elements by simply inlining it:

```html
<html>
    <head>
        <style>
            .blue-box
            {
                background-color: #0000FF;
                width: 100px;
                height: 100px;
            }
        </style>
    </head>
    <body>
        <div class="blue-box">this will be a blue box</div>
    </body>
</html>
```

***

```{=html}
<style>
  .blue-box {
    background-color: #0000ff;
    width: 100px;
    height: 100px;
  }
</style>
<div class="blue-box">this will be a blue box</div>
```

***

`css` statements consists of `selector` statement followed by a style statement between `{ }`. 

::: {.content-visible unless-format="revealjs"}
Selectors specify which `html` elements the style should apply to. Selectors can be specified to apply to all elements with certain `class` attribute, to elements with certain `id` attribute or to all elements of certain type.

On top of that these rules can be nested by chaining selectors separated by an empty space. For example rule with selector `.blue-box .white-box` would apply to all elements with `class` name `white-box` that are children of element of class `blue-box`.

Rules can also be used in conjunction: `.white-box.blue-box` would apply to elements that have both `white-box` and `blue-box` classes.

For the full reference of available rules see [this](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors).
:::

::: {.fragment}
`.blue-box` select and element with `class` = `blue-box`
:::

::: {.fragment}
`#id-name` select an element with `id` = `id-name`
:::

::: {.fragment}
`[data-attribute=value]` select an element with `data-attribute` attribute equal to `value`
:::

::: {.fragment}
Selectors can be chained and combined to target more specific elements. For example, `.blue-box .white-box` targets all elements with `class` = `white-box` that are descendants of elements with `class` = `blue-box`.
:::

***

CSS selectors are also used more broadly in JavaScript and other languages when selecting HTML elements.

To get the hang of `css` selectors, you can try a simple game like such [https://flukeout.github.io/](https://flukeout.github.io/).

***

To import `css` into an `html` document a `<link rel="stylesheet" href="style.css">` element should be added as child of `<head>` element. In this case `href` value (in the example it is `style.css`) specifies relative or absolute path of the `css` file to be imported into the `html` document.

An example

File `style.css`:

```css
.blue-box {
  background-color: #0000ff;
  width: 100px;
  height: 100px;
}
```

File `page.html`:

```html
<html>
  <head>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <div class="blue-box">this will be a blue box</div>
  </body>
</html>
```

***

*Better* practices when using `css`:

- Try to use selectors that use `class` names when targeting specific `html` elements.
- Link `css` from a file rather than inlining on `html` elements.
- Use [flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) to achieve the wanted page layout.

***
#### Aligning elements
HTML:
```html
<div class="container">
  <div class="blue-box">Blue Box</div>
  <div class="white-box">White Box</div>
</div>
```

CSS:
```css
.container {
  display: flex;
  justify-content: space-between;
}
.blue-box {
  background-color: #0000ff;
  width: 100px;
  height: 100px;
}
.white-box {
  background-color: #ffffff;
  width: 100px;
  height: 100px;
}
```

***

```{=html}
<style>
  .flexy-container {
    display: flex;
    justify-content: space-between;
  }
  .blue-box {
    background-color: #0000ff;
    width: 100px;
    height: 100px;
  }
  .white-box {
    background-color: #ffffff;
    width: 100px;
    height: 100px;
  }
</style>
<div class="flexy-container">
  <div class="blue-box">Blue Box</div>
  <div class="white-box">White Box</div>
</div>
```

### JavaScript

JavaScript is used to add dynamic functionality to the web sites.

Browsers have a capability to execute JavaScript (`js`) scripts that are added to the `html` document to give the website dynamic interactions. `js` is being executed on the client side (user's computer) and is the driving force behind the interactivity in the modern websites.

***

`js` can access `document` api and other predefined functions in the browser to alter the `html` document and perform other actions. Things `js` can do include:

- Dynamically add or remove `html` element from the document.
- Change the content of existing `html` elements.
- Call web services to fetch or send data.
- Do any calculations (JavaScript is proper Turing-complete language).

***

JavaScript can be imported to `html` document via `<script>` element in the `<head>`:

```html
<html>
  <head>
    <script src="javascript.js"></script>
    <script>
      alert("inline alert");
    </script>
  </head>
  <body></body>
</html>
```

::: {.content-visible unless-format="revealjs"}
The `html` document in the example above would import the `javascript.js` file with all the scripts inside of it and then would run the inline written script with `alert("inline alert");` (it would make an alert box pop up) statement.
:::

***

Example for javascript uses:

```{=html}
<script>
// Array of messages to show off JavaScript capabilities
const messages = [
  "✅ JS can update HTML!",
  "🕒 Current time: " + new Date().toLocaleTimeString(),
  "🔄 Dynamically change styles",
  "🎲 Random number: " + Math.floor(Math.random() * 100),
  "🌍 It can handle dates, numbers, text..."
];

let i = 0;
setInterval(() => {
  const box = document.getElementById("demo-box");

  // Cycle through messages
  const msg = messages[i % messages.length];
  box.innerHTML = msg;

  if (msg.startsWith("🕒")) {
  box.innerHTML = "🕒 Current time: " + new Date().toLocaleTimeString();
  }
  else if (msg.startsWith("🎲")) {
  box.innerHTML = "🎲 Random number: " + Math.floor(Math.random() * 100);
  }

  // Change box color randomly
  box.style.backgroundColor = `hsl(${Math.random() * 360}, 70%, 90%)`;

  i++;
  }, 1000);
</script>
<div id="demo-box">
  Waiting for update...
</div>
```

***

```html
<script>
// Array of messages to show off JavaScript capabilities
const messages = [
  "✅ JS can update HTML!",
  "🕒 Current time: " + new Date().toLocaleTimeString(),
  "🔄 Dynamically change styles",
  "🎲 Random number: " + Math.floor(Math.random() * 100),
  "🌍 It can handle dates, numbers, text..."
];

let i = 0;
setInterval(() => {
  const box = document.getElementById("demo-box");

  // Cycle through messages
  const msg = messages[i % messages.length];
  box.innerHTML = msg;

  if (msg.startsWith("🕒")) {
  box.innerHTML = "🕒 Current time: " + new Date().toLocaleTimeString();
  }
  else if (msg.startsWith("🎲")) {
  box.innerHTML = "🎲 Random number: " + Math.floor(Math.random() * 100);
  }

  // Change box color randomly
  box.style.backgroundColor = `hsl(${Math.random() * 360}, 70%, 90%)`;

  i++;
  }, 1000);
</script>
<div id="demo-box">
  Waiting for update...
</div>
```

### Calling Web APIs

```html
<div id="fact"></div>
<button onclick="getNewFact()">Get New Fact</button>
<script>
  function getNewFact() {
    let x = new XMLHttpRequest();
    x.open("GET", "https://catfact.ninja/fact");
    x.onload = () =>
      (document.getElementById("fact").innerText = JSON.parse(x.response).fact);
    x.send();
  }
</script>
```

***

```{=html}
<div id="fact"></div>
<button onclick="getNewFact()">Get New Fact</button>
<script>
  function getNewFact() {
    let x = new XMLHttpRequest();
    x.open("GET", "https://catfact.ninja/fact");
    x.onload = () =>
      (document.getElementById("fact").innerText = JSON.parse(x.response).fact);
    x.send();
  }
</script>
```

### WebSockets

Due to the nature and history of protocols used, web development was predominantly based on request-response model for the communication between client and the server.

However this may not be the most efficient approach, especially when the frontend wants to update the data frequently.

::: {.content-visible unless-format="revealjs"}
For example - think about the live chat applications. User would typically expect to see the message as soon as the other user sends it. Using the typical request-response pattern this would mean that client needs to ask the server (poll) if there are any new messages every few seconds. The lower the interval between requests the lower would be the delay, but at the same time - the more requests would just have blank responses.

Using the request-response approach there is a trade-off between wasting resources and introducing delay to the user. However braking free from the request-response model can enables us to have both - not wasting the resources and presenting the information in a timely manner.

WebSockets enables webapps to use two way communication with the server. Using the two way communication, the server can "push" the information to the client, without the client explicitly asking for it first.

Although the WebSockets technology is not exclusive to web user interfaces, it is widely used in web development, when frequent updates are required from the server to the web client.
:::

***

```{mermaid}
graph LR
    subgraph ClientSide
        C[Client]
    end

    subgraph ServerSide
        S[Server]
    end

    %% Persistent WebSocket connection (bidirectional)
    C ---|WebSocket connection| S
    %% Client requests
    C -->|Client request| S
    %% Server pushes data
    S -->|Server push| C

    style C fill:#61bffc,stroke:#333,stroke-width:2px,color:#fff
    style S fill:#ff4136,stroke:#333,stroke-width:2px,color:#fff

```

## Ways of rendering the `html` documents

::: {.content-visible unless-format="revealjs"}
`HTML` documents have 2 major options how they can be rendered:
:::

1. Server side
2. Client side

::: {.fragment}
Both of these options has their own pros and cons, and none of them is supperior to the other.
:::

### Server side rendering

Traditional way of rendering the `html` documents is rendering them on the server side. This means that all or the majority of `html` document is assembled on the server side, however some smaller part of the document can still be created or manipulated by the `javascript` on the client side.

***

In case of server side rendering, the server can simply return differnt `html` on each request. After reloading the page a different rendered view would be seen.

```csharp
if (hi is true)
{
    return "<html>Hello world</html>";
}
else
{
    return "<html>Goodbye</html>";
}
```

***

Server-side rendering has such advantages as:

::: {.fragment}
- An ability to cache the rendered websites on the server side so they could be served faster for the future users.
:::
::: {.fragment}
- If rendering of the websites requires lots of data from the server, this might be faster because there would be less latency when fetching the data from the server, since all the action is happening in the server itself.
:::
::: {.fragment}
- Server, as a machine, might be faster than the consumer device, which might speed up the calculations needed to assemble the `html` document in certain cases. 
:::

### Client side rendering

Client side rendering is done by the `javascript` or *similar other language*[^1] on the user's browser.

::: {.fragment}
1. Very basic `html` is returned with the initial `document` load.
:::
::: {.fragment}
2. Document asks scripts to be loaded.
:::
::: {.fragment}
3. Scripts start fetching the needed data from Web APIs.
:::
::: {.fragment}
4. Scripts assemble the `html` document on the client's machine.
:::

***

 There are popular SPA (single page application) frameworks for this purpose, like:
 
- `react.js`
- `angular`
- `vue.js`

***

In case of client side rendering, the `html` document would be constructed on the client side (in this case the "client side" is simply a web browser).

The logic needed to modify the document would written in `JavaScript`, `WASM` or some derrivative language.

***

```html
<nav>
  <button onclick="show('fact')">Fact</button>
  <button onclick="show('breeds')">Breeds</button>
</nav>
<div id="app"></div>
<script>
  const app = document.getElementById("app");
  const getJson = async (url) => (await fetch(url)).json();

  const pages = {
    fact: async () => `<p>${(await getJson("https://catfact.ninja/fact")).fact}</p>`,
    breeds: async () => {
      const { data } = await getJson("https://catfact.ninja/breeds?limit=5");
      return `<ul>${data.map((b) => `<li>${b.breed}</li>`).join("")}</ul>`;
    },
  };

  async function show(page) {
    app.innerHTML = "Loading...";
    app.innerHTML = await pages[page]();
  }

  show("fact");
</script>
```

***

```{=html}
<nav>
  <button onclick="show('fact')">Fact</button>
  <button onclick="show('breeds')">Breeds</button>
</nav>
<div id="app"></div>
<script>
  const app = document.getElementById("app");
  const getJson = async (url) => (await fetch(url)).json();

  const pages = {
    fact: async () => `<p>${(await getJson("https://catfact.ninja/fact")).fact}</p>`,
    breeds: async () => {
      const { data } = await getJson("https://catfact.ninja/breeds?limit=5");
      return `<ul>${data.map((b) => `<li>${b.breed}</li>`).join("")}</ul>`;
    },
  };

  async function show(page) {
    app.innerHTML = "Loading...";
    app.innerHTML = await pages[page]();
  }

  show("fact");
</script>
```

***

Client side rendering offers advantages like:

::: {.fragment}
- Increased level of interactivity of the website. This allows to easily add interaction to `html` elements that would be handled on the client side.
:::
::: {.fragment}
- Initial latency might be reduced. Because a very simple document is only loaded initially, some loading state indicator can be displayed on screen very quickly. To fully render the website will still take time, but the first interactive version can be displayed very quickly.
:::
::: {.fragment}
- Potentially reduced computational load on the server side.
:::

^1 - there are options like compiled web assemblies (wasm), that are not `javascript`, but can be used for similar purposes.

### Pitch for client side rendering

::: {.fragment}
1. You already have a server, so you just return HTML, since it's easier
:::
::: {.fragment}
2. You want to have some interactivity, so you just add random JavaScript inserts here and there
:::
::: {.fragment}
3. There becomes a lot of JavaScript inserts
:::
::: {.fragment}
4. Now you are have sort of backend code, but it is in 2 languages and they don't integrate seamlessly
:::
::: {.fragment}
5. You decide to hard separate them
:::
::: {.fragment}
6. Might as well download all the JavaScript at once
:::
::: {.fragment}
7. ...
:::

## Further reading

- https://thecascade.dev/article/least-amount-of-css/ - the least amount of CSS to get decent improvement over defaults.
